### PR TITLE
Dynamically generate methods on concrete classes only

### PR DESCRIPTION
**Pull request by gap777**
Avoid creating public methods on instances of the base class itself, so that derived types don't interfere with each other

### CODE REVIEW

**Comment by gap777** [comment]
@etagwerker @benphelps @mscottford can we get some response to this? Seems like a few PRs have stalled.

**Comment by benphelps** [comment]
I'm waiting for your other requests to be merged before I continue on with anything of mine as changes will be required on my end.

**Comment by lubc** [comment]
@gap777 hey, can you fix the conflicts in this PR so we can merge it? Thanks!

**Comment by etagwerker** [comment]
@gap777 Great, thank you! 👍

**Pull request merged**
