### PR TITLE
Add ability to fetch next page with persisted query parameters

### PR DESCRIPTION
**Pull request by dsul**
When requesting a new page of results (Not page 1), the query parameters are not persisted which leads to incorrect results. This PR intends to persist the initial query parameters that were correctly passed into the API request for the first page, along to the subsequent API requests for the rest of the pages of results.

### CODE REVIEW

**Comment by gap777** [comment]
@etagwerker @benphelps @mscottford can we get some response to this? Seems like a few PRs have stalled.

**Comment by gap777** [comment]
@etagwerker should we update this to master as the next PR to discuss?

**Comment by etagwerker** [comment]
@gap777 Yes, that's a good idea. Thanks!

**Comment by gap777** [comment]
@etagwerker Rebased onto your master, but getting a test failure in 

```
1) Harvesting::Client#me returns the authenticated user
     Failure/Error: expect(user.first_name).to eq(account_first_name)

       expected: "<replace me with a test account>"
            got: "123"

       (compared using ==)
     # ./spec/harvesting/client_spec.rb:107:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:32:in `block (3 levels) in <top (required)>'
     # ./spec/spec_helper.rb:32:in `block (2 levels) in <top (required)>'
```

I'm suspecting that's just an environmental issue, though. Can you try on your machine, and if all is well, merge?

**Comment by etagwerker** [comment]
@gap777 Cool, thanks! I fixed that failing spec in this commit: https://github.com/ombulabs/harvesting/commit/a0a37333f7f5371400487377da92252cd92f34a0

**Pull request merged**
